id: IDADF0D0A
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:08:29.400121+00:00
last_modified: 2022-12-14 18:08:29.400126+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-068-020
  eft-text-version: 1.1.3 2020
  title: Toh_286-The_Dedication_Protecting_All_Beings-v2
bases:
  A93C:
    source_metadata: null
    order: 1
    base_file: A93C.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
